### ISSUE TITLE
positive values of rootMargin needs to be used to expand the intersection root

### ISSUE THREAD

**Issue by sreedhar7** [linkedin/spaniel#24]
From the spec at https://wicg.github.io/IntersectionObserver/

> For any target which belongs to the same unit of related similar-origin browsing contexts as the intersection root, the rectangle is then expanded according to the offsets in the IntersectionObserver’s [[rootMargin]] slot in a manner similar to CSS’s margin property, with the four values indicating the amount the top, right, bottom, and left edges, respectively, are offset by, with positive lengths indicating an outward offset. Percentages are resolved relative to the width of the undilated rectangle.

Currently if we set the bottom rootMargin to a positive value the intersection root is shrinked instead of expanded.

**Comment by rwwagner90** [comment]
+1 I am seeing this same issue

**Comment by asakusuma** [comment]
Fixed as of `3.0.0`
