### ISSUE TITLE
Scroll debouncer

### ISSUE THREAD

**Issue by teterovic** [linkedin/spaniel#39]
I'm using the IntersectionObserver polyfill to lazyload images on tiles. The problem is I have a few thousand tiles each one with a image on it that needs to be lazyloaded.

Previously I used a scroll debouncer to load the image only when the scroll stops which was gave huge improvement in performance.

The question is how to use a scroll debouncer together with IntersectionObserver?

One solution but a stupid one is to create a preliminary array of visible items and add a timeout

**Comment by teterovic** [comment]
Ok i found a recipe but it's still not fitting perfectly

> function query(selector) {
>   return Array.from(document.querySelectorAll(selector));
> }
> 
> var observer = new IntersectionObserver(
>   // Pre-load items that are within 2 multiples of the visible viewport height.
>   function(changes) {
>     changes.forEach(function(change) {
>       var container = change.target;
>       var content = container.querySelector("template").content;
>       container.appendChild(content);
>       observer.unobserve(container);
>     });
>   },
>   { rootMargin: "200% 0" }
> );
> 
> // Debouncer calls this:
> query(".lazy-loaded").forEach(function(item) {
>   observer.observe(item);
> });

**Comment by asakusuma** [comment]
You could create invisible markers, observer the markers, and prevent loading of any images that aren't below the highest nonvisible marker.

**Comment by asakusuma** [comment]
Closing this for now, feel free to re-open if needed.
