### ISSUE TITLE
Watcher support for elements not within the DOM

### ISSUE THREAD

**Issue by lynchbomb** [linkedin/spaniel#76]
Spaniel v2.4.6 does not provide support for elements being watched that are not within the DOM. Currently the `ElementScheduler` caches `getBoundingClientRect` which is set during the `watch` phase. Elements not yet within the DOM return default values on `getBoundingClientRect` which are then cached within the `ElementScheduler`. 

https://github.com/linkedin/spaniel/blob/f2c580b30c22af4a6337e98291c0f7d651e19352/src/metal/scheduler.ts#L176-L188

Thoughts on exposing a method within Spaniel to force a revalidation of cached `getBoundingClientRect` on elements being watched? Either on the `Watcher` or exposing the `W` (window proxy).

**Comment by stefanpenner** [comment]
> Thoughts on exposing a method within Spaniel to force a revalidation of cached getBoundingClientRect on elements being watched? Either on the Watcher or exposing the W (window proxy).

To make sure we solve this correctly, do you mind providing 1 or 2 examples of needing this functionality. That way we can make sure we are solving the right problem.

**Comment by lynchbomb** [comment]
The seemingly legit use-case is via lazy loading images with fixed dimensions and ghosting. Something like leveraging `Ember-Spaniel#onInViewportOnce` for implementation which would leverage the `Spaniel#ElementScheduler`.

**Comment by lynchbomb** [comment]
DM with @stefanpenner:
So one question would be, in theory could `Ember-Spaniel#onInViewport` be leveraged only when the lazy loaded image is in the DOM? Assuming it was properly detached. Hypothetically this would work around the IE11 bug entirely (https://github.com/linkedin/spaniel/issues/75). 

In addition we may actually want to consider making Spaniel (in dev) explode if `Watcher` tries to watch something detached from the DOM.

**Comment by stefanpenner** [comment]
I believe that is safe, and would be an "honest" cross browser implementation, as it would only support what it could safely support across its browsers.  Eventually if IE11 is dropped, we could choose to loosen.

**Comment by lynchbomb** [comment]
After DMing with @krisselden another proposed solve would be removing the caching of `getBoundingClientRect` during the init of `ElementScheduler#watch`. Keeping the ideal of nothing in the read queue should cause a run loop, set() or manipulate the DOM. Nothing outside the queue should read from the DOM only memoized state from read queue.

https://github.com/linkedin/spaniel/blob/v2-release/src/metal/scheduler.ts#L162-L188

If we set `clientRect` to `null` here: https://github.com/linkedin/spaniel/blob/v2-release/src/metal/scheduler.ts#L179

and memoized `clientRect` within the `ElementScheduler#applyQueue` (read queue) this issue should be solved.

**Comment by lynchbomb** [comment]
This PR: https://github.com/linkedin/spaniel/pull/79 should address this issue.
